version: '3.7'

services:

  deconz:
    container_name: deconz
    image: marthoc/deconz
    restart: unless-stopped
    environment:
      - "TZ=${TIMEZONE}"
      - "DECONZ_WEB_PORT=${DECONZ_WEB_PORT}"
      - "DECONZ_VNC_MODE=${DECONZ_VNC_MODE}"
      - "DECONZ_VNC_PORT=${DECONZ_VNC_PORT}"
      - "DECONZ_VNC_PASSWORD=${DECONZ_VNC_PASSWORD}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - deconz_data:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    # network_mode: host
    ports:
      - "8080:8080"
      - "5900:5900"
    networks:
      smarthome-network:
        aliases:
          - deconz
    healthcheck:
      test: ["CMD", "curl", "-I", "--silent", "--show-error", "--fail", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 6

networks:
  smarthome-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: smarthome-br
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.16.0}.0/24

volumes:
  deconz_data:
